name: 2ShipPlayer
description: Default 2 Ship 2 Harkinian Archipelago settings
game: 2 Ship 2 Harkinian
requires:
  version: 0.6.7

2 Ship 2 Harkinian:
  progression_balancing: 50
  accessibility: full
  start_inventory_from_pool:
    Ocarina: 1
    Song of Time: 1
    Progressive Sword: 1
    Shield Hero: 1
  check_scope: core
  logic_mode: glitchless
  shuffle_boss_remains: true
  moon_remains_required: 4
  skeleton_key: false
